# Generated by Django 3.1.3 on 2020-12-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='default', max_length=800),
            preserve_default=False,
        ),
    ]
