# Generated by Django 3.1.3 on 2020-12-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('college_img', models.ImageField(upload_to='')),
                ('college_duration', models.CharField(max_length=300)),
            ],
        ),
    ]
